name: CI - Run Pytest Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Install Google Chrome (Needed in GitHub Actions)
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      # 5. Install ChromeDriver (webdriver_manager uses it later)
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 4. Run API tests
      - name: Run API tests
        run: pytest api_tests/ -v --maxfail=1 --disable-warnings || true

      # 5. Run UI tests (headless)
      - name: Run UI tests
        run: |
          pytest ui_tests/ -v --maxfail=1 --disable-warnings --headless
